import Fluent
import Vapor

/// A potential notification for a user, generated by a Phase 2B/2C/2D candidate generator
/// (none exist yet in Phase 2A) and consumed by the dispatch pass, which selects at most
/// one candidate per user per send slot via `CandidateRanking`.
final class NotificationCandidate: Model, @unchecked Sendable {
    static let schema = "notification_candidates"
    static let defaultDatabase: DatabaseID? = .notifications

    @ID(key: .id) var id: UUID?

    @Field(key: "user_id") var userId: UUID

    /// e.g. "brobot_followup_24h", "learning_daily" — see `CandidateSourceType`.
    @Field(key: "source_type") var sourceType: String

    /// The conversation_id / question_id / pearl_id this candidate is about.
    /// Nullable for source types with no specific referenced row (e.g. a static daily pearl).
    /// NOTE: the DB-level dedup constraint coalesces NULL to a sentinel UUID so two candidates
    /// of the same (user_id, source_type) with no source_ref_id still collide correctly —
    /// see CreateNotificationCandidates for detail. Generators do not need to invent a
    /// synthetic ref_id themselves.
    @OptionalField(key: "source_ref_id") var sourceRefId: UUID?

    @Field(key: "category") var category: String

    /// Fine-grained type, e.g. "learning.daily_pearl" — joins against `notification_templates`.
    /// Phase 2A only had `source_type` (the broader bucket); added in Phase 2B.
    @OptionalField(key: "notification_type") var notificationType: String?

    @Field(key: "priority_score") var priorityScore: Int

    @Field(key: "payload") var payload: [String: String]

    @Field(key: "eligible_at") var eligibleAt: Date

    @Field(key: "expires_at") var expiresAt: Date

    @Field(key: "status") var status: CandidateStatus

    @Timestamp(key: "created_at", on: .create) var createdAt: Date?

    init() {}

    init(
        id: UUID? = nil,
        userId: UUID,
        sourceType: String,
        sourceRefId: UUID? = nil,
        category: NotificationCategory,
        notificationType: String? = nil,
        priorityScore: Int,
        payload: [String: String] = [:],
        eligibleAt: Date,
        expiresAt: Date,
        status: CandidateStatus = .pending
    ) {
        self.id = id
        self.userId = userId
        self.sourceType = sourceType
        self.sourceRefId = sourceRefId
        self.category = category.rawValue
        self.notificationType = notificationType
        self.priorityScore = priorityScore
        self.payload = payload
        self.eligibleAt = eligibleAt
        self.expiresAt = expiresAt
        self.status = status
    }

    enum CandidateStatus: String, Codable, Sendable {
        case pending
        case sent
        case expired
        case superseded
        case cooldownBlocked = "cooldown_blocked"
    }
}
